/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GalleryEvent = {
  _id: string;
  _type: "galleryEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  location?: string;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PrintArtwork = {
  _id: string;
  _type: "printArtwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  badge?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sizes?: Array<string>;
  description?: string;
  productType?: "print" | "poster" | "sticker" | "merch";
  tags?: Array<string>;
  orderRank?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "photo" | "design" | "art";
  description?: string;
  items?: Array<string>;
  cta?: string;
  ctaService?: string;
  orderRank?: number;
};

export type PracticePillar = {
  _id: string;
  _type: "practicePillar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "art" | "design" | "photo";
  tagline?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderRank?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "art" | "design" | "photo";
  subcategory?: string;
  description?: string;
  year?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tags?: Array<string>;
  isCaseStudy?: boolean;
  caseStudy?: {
    summary?: string;
    phases?: Array<{
      title?: string;
      description?: string;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }>;
      _key: string;
    }>;
  };
};

export type CreativeSignature = {
  _id: string;
  _type: "creativeSignature";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sectionLabel?: string;
  headingLine1?: string;
  headingLine2?: string;
  description?: string;
  step1?: {
    badge?: string;
    title?: string;
    tagline?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  step2?: {
    badge?: string;
    title?: string;
    tagline?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  step3?: {
    badge?: string;
    title?: string;
    tagline?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  ctaText?: string;
  ctaLink?: string;
};

export type HeroSettings = {
  _id: string;
  _type: "heroSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  subheading?: string;
  badge?: string;
  categoryTags?: Array<string>;
  primaryCtaText?: string;
  secondaryCtaText?: string;
  secondaryCtaLink?: string;
  footerTagline?: string;
  slides?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GalleryEvent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PrintArtwork
  | Service
  | PracticePillar
  | Project
  | CreativeSignature
  | HeroSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: HERO_SETTINGS_QUERY
// Query: *[_type == "heroSettings"][0] {    _id,    headline,    subheading,    badge,    categoryTags,    primaryCtaText,    secondaryCtaText,    secondaryCtaLink,    footerTagline,    slides[] {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    }  }
export type HERO_SETTINGS_QUERY_RESULT = {
  _id: string;
  headline: string | null;
  subheading: string | null;
  badge: string | null;
  categoryTags: Array<string> | null;
  primaryCtaText: string | null;
  secondaryCtaText: string | null;
  secondaryCtaLink: string | null;
  footerTagline: string | null;
  slides: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: CREATIVE_SIGNATURE_QUERY
// Query: *[_type == "creativeSignature"][0] {    _id,    sectionLabel,    headingLine1,    headingLine2,    description,    step1 {      badge,      title,      tagline,      description,      image {          asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop      }    },    step2 {      badge,      title,      tagline,      description,      image {          asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop      }    },    step3 {      badge,      title,      tagline,      description,      image {          asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop      }    },    ctaText,    ctaLink  }
export type CREATIVE_SIGNATURE_QUERY_RESULT = {
  _id: string;
  sectionLabel: string | null;
  headingLine1: string | null;
  headingLine2: string | null;
  description: string | null;
  step1: {
    badge: string | null;
    title: string | null;
    tagline: string | null;
    description: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  step2: {
    badge: string | null;
    title: string | null;
    tagline: string | null;
    description: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  step3: {
    badge: string | null;
    title: string | null;
    tagline: string | null;
    description: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  ctaText: string | null;
  ctaLink: string | null;
} | null;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(year desc, _createdAt desc) {    _id,    title,    "slug": slug.current,    category,    subcategory,    description,    year,    tags,    isCaseStudy,    coverImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  category: "art" | "design" | "photo" | null;
  subcategory: string | null;
  description: string | null;
  year: string | null;
  tags: Array<string> | null;
  isCaseStudy: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    category,    subcategory,    description,    year,    tags,    isCaseStudy,    coverImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    },    images[] {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    },    caseStudy {      summary,      phases[] {        _key,        title,        description,        images[] {            asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop        }      }    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  category: "art" | "design" | "photo" | null;
  subcategory: string | null;
  description: string | null;
  year: string | null;
  tags: Array<string> | null;
  isCaseStudy: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  caseStudy: {
    summary: string | null;
    phases: Array<{
      _key: string;
      title: string | null;
      description: string | null;
      images: Array<{
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: PRACTICE_PILLARS_QUERY
// Query: *[_type == "practicePillar"] | order(orderRank asc, _createdAt asc) {    _id,    title,    category,    tagline,    description,    image {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    }  }
export type PRACTICE_PILLARS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  category: "art" | "design" | "photo" | null;
  tagline: string | null;
  description: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(orderRank asc, _createdAt asc) {    _id,    title,    description,    category,    items,    cta,    ctaService  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  category: "art" | "design" | "photo" | null;
  items: Array<string> | null;
  cta: string | null;
  ctaService: string | null;
}>;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: PRINTS_QUERY
// Query: *[_type == "printArtwork"] | order(orderRank asc, _createdAt asc) {    _id,    title,    "slug": slug.current,    badge,    sizes,    description,    productType,    tags,    image {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    }  }
export type PRINTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  badge: string | null;
  sizes: Array<string> | null;
  description: string | null;
  productType: "merch" | "poster" | "print" | "sticker" | null;
  tags: Array<string> | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "galleryEvent" && defined(slug.current)] | order(date desc) {    _id,    title,    "slug": slug.current,    date,    location,    description,    coverImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    },    "photoCount": count(photos)  }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  location: string | null;
  description: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  photoCount: number | null;
}>;

// Source: ../DK-Portfolio/src/sanity/queries.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "galleryEvent" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    date,    location,    description,    coverImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    },    photos[] {      _key,        asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop    }  }
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  location: string | null;
  description: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  photos: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "heroSettings"][0] {\n    _id,\n    headline,\n    subheading,\n    badge,\n    categoryTags,\n    primaryCtaText,\n    secondaryCtaText,\n    secondaryCtaLink,\n    footerTagline,\n    slides[] {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': HERO_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "creativeSignature"][0] {\n    _id,\n    sectionLabel,\n    headingLine1,\n    headingLine2,\n    description,\n    step1 {\n      badge,\n      title,\n      tagline,\n      description,\n      image {\n        \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n      }\n    },\n    step2 {\n      badge,\n      title,\n      tagline,\n      description,\n      image {\n        \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n      }\n    },\n    step3 {\n      badge,\n      title,\n      tagline,\n      description,\n      image {\n        \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n      }\n    },\n    ctaText,\n    ctaLink\n  }\n': CREATIVE_SIGNATURE_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)] | order(year desc, _createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    subcategory,\n    description,\n    year,\n    tags,\n    isCaseStudy,\n    coverImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    subcategory,\n    description,\n    year,\n    tags,\n    isCaseStudy,\n    coverImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    images[] {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    caseStudy {\n      summary,\n      phases[] {\n        _key,\n        title,\n        description,\n        images[] {\n          \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n        }\n      }\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "practicePillar"] | order(orderRank asc, _createdAt asc) {\n    _id,\n    title,\n    category,\n    tagline,\n    description,\n    image {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': PRACTICE_PILLARS_QUERY_RESULT;
    '\n  *[_type == "service"] | order(orderRank asc, _createdAt asc) {\n    _id,\n    title,\n    description,\n    category,\n    items,\n    cta,\n    ctaService\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "printArtwork"] | order(orderRank asc, _createdAt asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    badge,\n    sizes,\n    description,\n    productType,\n    tags,\n    image {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': PRINTS_QUERY_RESULT;
    '\n  *[_type == "galleryEvent" && defined(slug.current)] | order(date desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    location,\n    description,\n    coverImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    "photoCount": count(photos)\n  }\n': EVENTS_QUERY_RESULT;
    '\n  *[_type == "galleryEvent" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    location,\n    description,\n    coverImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    },\n    photos[] {\n      _key,\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n\n    }\n  }\n': EVENT_BY_SLUG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
